public enum E_BATTLE_REAL_STATE
{
    START,
    GAME,
    DEAD,
    CHARGE_SHOT,
    BEGIN_BOSS_BATTLE,
    TO_HACKING,
    STAY_HACKING,
    FROM_HACKING,
    WAIT_CUTSCENE,
    WAIT_TALK,
    WAIT_DIALOG,
    OPEN_MENU,
    GAME_CLEAR,
    GAME_OVER,
    END,
}