public enum E_BATTLE_REAL_STATE
{
    START,
    BEFORE_BEGIN_GAME,
    BEFORE_BEGIN_GAME_PERFORMANCE,
    BEGIN_GAME,
    GAME,
    DEAD,
    BEFORE_BOSS_BATTLE_PERFORMANCE,
    STAY_HACKING,
    BEFORE_GAME_CLEAR_PERFORMANCE,
    GAME_CLEAR,
    GAME_OVER,
    END,
}