public enum E_BATTLE_REAL_STATE
{
    START,
    BEFORE_BEGIN_GAME,
    BEFORE_BEGIN_GAME_PERFORMANCE,
    BEGIN_GAME,
    GAME,
    DEAD,
    CHARGE_SHOT_PERFORMANCE,
    BEFORE_BOSS_BATTLE_PERFORMANCE,
    TRANSITION_TO_HACKING,
    STAY_HACKING,
    TRANSITION_TO_REAL,
    BEFORE_GAME_CLEAR_PERFORMANCE,
    GAME_CLEAR,
    GAME_OVER,
    END,
}