// <auto-generated>
// Rewired Constants
// This list was generated on 2020/05/17 21:34:24
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // KeyCon
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "KeyCon", friendlyName = "Horizontal")]
        public const int KeyCon_Horizontal = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "KeyCon", friendlyName = "Vertical")]
        public const int KeyCon_Vertical = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "KeyCon", friendlyName = "OK")]
        public const int KeyCon_OK = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "KeyCon", friendlyName = "Cancel")]
        public const int KeyCon_Cancel = 14;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Horizontal")]
        public const int UI_Horizontal = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Vertical")]
        public const int UI_Vertical = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "OK")]
        public const int UI_OK = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Cancel")]
        public const int UI_Cancel = 3;
        // InGame
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "InGame", friendlyName = "Horizontal")]
        public const int Horizontal = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "InGame", friendlyName = "Vertical")]
        public const int Vertical = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "InGame", friendlyName = "Shot")]
        public const int Shot = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "InGame", friendlyName = "Charge Shot")]
        public const int ChargeShot = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "InGame", friendlyName = "Change Weapon")]
        public const int ChangeWeapon = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "InGame", friendlyName = "Slowly Move")]
        public const int Slowly_Move = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "InGame", friendlyName = "Menu Open")]
        public const int Menu_Open = 10;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int KeyCon = 3;
        public const int UI = 5;
        public const int InGame = 2;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
