[System.Serializable]
public enum E_CUE_NAME
{
    BGM_TITLE,
    BGM_TUTORIAL,
    BGM_STAGE_01,
    BGM_BOSS_01,
    BGM_CLEAR,
    BGM_GAMEOVER,

    SE_PLAYER_SHOT_01,
    SE_PLAYER_HACK_SHOT_01,
    SE_PLAYER_WEAPON_CHANGE,
    SE_PLAYER_CHARGE,
    SE_PLAYER_LASER,
    SE_PLAYER_BOMB,
    SE_PLAYER_GET_ITEM,
    SE_PLAYER_HIT,

    SE_ENEMY_SHOT_01,
    SE_ENEMY_SHOT_02,
    SE_ENEMY_LASER_01,
    SE_ENEMY_DAMAGE,
    SE_ENEMY_BREAK_01,
    SE_ENEMY_DOWN,
    SE_ENEMY_HACK_SHOT_01,
    SE_ENEMY_HACK_SHOT_02,

    SE_GLOBAL_HACK_START,
    SE_GLOBAL_HACK_END,
    SE_GLOBAL_PAWER_UP,

    SE_SYSTEM_CURSOR,
    SE_SYSTEM_OK,
    SE_SYSTEM_CANCEL,
    SE_SYSTEM_START,
}
